{% set name = "barril" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 535701a0f60e4410335d2f2f04f6e7ed4853a384603565e22fae93760687225a

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - attrs >=18.1.0
    - numpy >=1.11.0
    - oop-ext >=1.1
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - barril
  requires:
    - pytest
    - pytest-mock
    - python {{ python_min }}
  commands:
    - pytest --pyargs barril

about:
  home: https://github.com/ESSS/barril
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to manage units for physical quantities

extra:
  recipe-maintainers:
    - igortg
    - kfasolin
    - lincrosenbach
    - nicoddemus
    - tadeu
    - jaimeambrus
    - williamjamir
