{% set name = "barril" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f595f1e9696a5514657b49b6f9902248ca22453254ed45a13bbf03b8e7b2d876

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - attrs >=18.1.0
    - numpy >=1.11.0
    - oop-ext >=0.2.4
    - python >=3.6
    - typing_extensions

test:
  imports:
    - barril
  requires:
    - pytest
    - pytest-mock
  commands:
    - pytest --pyargs barril

about:
  home: https://github.com/ESSS/barril
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package to manage units for physical quantities

extra:
  recipe-maintainers:
    - igortg
    - kfasolin
    - lincrosenbach
    - nicoddemus
    - tadeu
    - jaimeambrus
    - williamjamir
